/** @type {import('@ladle/react').UserConfig} */
export default {
  storyOrder: [
    "doc--guide",
    "grid--simple",
    "grid--sizing",
    "grid--styling",
    "grid--custom-aria-labels",
    "grid--sorting",
    "grid--filtering",
    "grid--column-resizing",
    "grid--grouped-columns",
    "grid--pinned-columns",
    "grid--cell-focus",
    "grid--cell-selection",
    "grid--cell-copy",
    "grid--programmatic-controls",
    "grid--virtual-rows",
    "grid--virtual-columns",
    "grid--row-spanning",
    "grid--column-spanning",
    "editing--simple",
    "editing--overflow-editors",
    "editing--pinned-and-spanned",
    "events--context-menu",
    "events--column-selection",
    "events--synced-scrolling",
    "styling--classes",
  ],
};
