import type { ColumnDef } from "./Grid";

export const colDefs: ColumnDef[] = [
  { field: 'propertyId', title: 'Property ID', width: 85 },
  { field: 'propertyName', title: 'Property Name', width: 110 },
  { field: 'bbl', title: 'NYC Borough, Block and Lot (BBL)', width: 200 },
  {
    field: 'bin',
    title: 'NYC Building Identification Number (BIN)',
    width: 275,
  },
  { field: 'address', title: 'Address 1', width: 75 },
  { field: 'city', title: 'City', width: 100 },
  { field: 'zip', title: 'Postal Code', width: 100 },
  {
    field: 'primaryPropertyType',
    title: 'Primary Property Type - Self-Selected',
    width: 250,
  },
  { field: 'primaryPropertyTypeArea', title: 'Largest Property Use Type - Gross Floor Area (ft²)' },
  { field: 'secondaryPropertyType', title: '2nd Largest Property Use Type' },
  { field: 'secondaryPropertyTypeArea', title: '2nd Largest Property Use Type - Gross Floor Area (ft²)' },
  { field: 'yearBuilt', title: 'Year Built', width: 70 },
  { field: 'numberOfBuildings', title: 'Number of Buildings', width: 130 },
  { field: 'occupancy', title: 'Occupancy', },
  { field: 'meteredAreasEnergy', title: 'Metered Areas (Energy)', },
  { field: 'meteredAreasWater', title: 'Metered Areas (Water)', },
  { field: 'energyStarScore', title: 'ENERGY STAR Score', },
  { field: 'oilUseNo1', title: 'Fuel Oil #1 Use (kBtu)', },
  { field: 'oilUseNo2', title: 'Fuel Oil #2 Use (kBtu)', },
  { field: 'steamUse', title: 'District Steam Use (kBtu)', },
  { field: 'hotWaterUse', title: 'District Hot Water Use (kBtu)', },
  { field: 'chilledWaterUse', title: 'District Chilled Water Use (kBtu)', },
  { field: 'naturalGasUse', title: 'Natural Gas Use (kBtu)', },
  { field: 'electricityUseGridPurchased', title: 'Electricity Use - Grid Purchase (kWh)', },
  { field: 'electricityUseGridPurchasedAndOnsiteGenerated', title: 'Electricity Use - Grid Purchase and Generated from Onsite Renewable Systems (kWh)', },
  { field: 'electricityUseOnsiteGeneratedUsed', title: 'Electricity Use – Generated from Onsite Renewable Systems and Used Onsite (kWh)', },
  { field: 'electricityUseOnsiteGenerated', title: 'Electricity Use – Generated from Onsite Renewable Systems (kWh)', },
  { field: 'electricityUseOnsiteGeneratedExported', title: 'Electricity Use – Generated from Onsite Renewable Systems and Exported (kWh)', },
  { field: 'greenPower', title: 'Green Power - Onsite and Offsite (kWh)', },
  { field: 'totalGHGEmissions', title: 'Total (Location-Based) GHG Emissions (Metric Tons CO2e)', },
  { field: 'directGHGEmissions', title: 'Direct GHG Emissions (Metric Tons CO2e)', },
  { field: 'indirectGHGEmissions', title: 'Indirect (Location-Based) GHG Emissions (Metric Tons CO2e)', },
  { field: 'netEmissions', title: 'Net Emissions (Metric Tons CO2e)', },
  { field: 'avoidedEmissions', title: 'Avoided Emissions - Onsite and Offsite Green Power (Metric Tons CO2e)', },
  { field: 'percentElectricityGeneratedFromRenewableOnsitePower', title: 'Percent of Total Electricity Generated from Onsite Renewable Systems', },
  { field: 'propertyNotes', title: 'Property Notes', },
  { field: 'waterUse', title: 'Water Use (All Water Sources) (kgal)', },
  { field: 'totalActiveEnergyMeters', title: 'Number of Active Energy Meters - Total', },
  { field: 'borough', title: 'Borough', },
  { field: 'latitude', title: 'Latitude', },
  { field: 'longitude', title: 'Longitude', },
  { field: 'councilDistrict', title: 'Council District', },
];

export const groupedColumnDefs: ColumnDef[] = [
  { field: 'property', title: 'Property', subcolumns: [  { field: 'propertyId', title: 'ID', width: 90 },{ field: 'propertyName', title: 'Name', width: 250 }]},
  { field: 'bbl', title: 'NYC Borough, Block and Lot (BBL)', width: 'max-content' },
  {
    field: 'bin',
    title: 'NYC Building Identification Number (BIN)',
    width: 'max-content',
  },
  { field: 'fullAddress', title: 'Address', subcolumns: [
    { field: 'address', title: 'Street', width: 'max-content' },
    { field: 'city', title: 'City', width: 100 },
    { field: 'zip', title: 'Postal Code', width: 100 },
  ]},
  {
    field: 'primaryPropertyType',
    title: 'Primary Property Type - Self-Selected',
    width: 250,
  },
  { field: 'primaryPropertyTypeArea', title: 'Largest Property Use Type - Gross Floor Area (ft²)' },
  { field: 'secondaryPropertyType', title: '2nd Largest Property Use Type' },
  { field: 'secondaryPropertyTypeArea', title: '2nd Largest Property Use Type - Gross Floor Area (ft²)' },
  { field: 'yearBuilt', title: 'Year Built', width: 70 },
  { field: 'numberOfBuildings', title: 'Number of Buildings', width: 130 },
  { field: 'occupancy', title: 'Occupancy', },
  { field: 'meteredAreas', title: 'Metered Areas', subcolumns: [
    { field: 'meteredAreasEnergy', title: 'Energy', },
    { field: 'meteredAreasWater', title: 'Water', },
  ]},
  { field: 'energyStarScore', title: 'ENERGY STAR Score', },
  { field: 'oilUseNo1', title: 'Fuel Oil #1 Use (kBtu)', },
  { field: 'oilUseNo2', title: 'Fuel Oil #2 Use (kBtu)', },
  { field: 'steamUse', title: 'District Steam Use (kBtu)', },
  { field: 'hotWaterUse', title: 'District Hot Water Use (kBtu)', },
  { field: 'chilledWaterUse', title: 'District Chilled Water Use (kBtu)', },
  { field: 'naturalGasUse', title: 'Natural Gas Use (kBtu)', },
  { field: 'electricityUseGridPurchased', title: 'Electricity Use - Grid Purchase (kWh)', },
  { field: 'electricityUseGridPurchasedAndOnsiteGenerated', title: 'Electricity Use - Grid Purchase and Generated from Onsite Renewable Systems (kWh)', },
  { field: 'electricityUseOnsiteGeneratedUsed', title: 'Electricity Use – Generated from Onsite Renewable Systems and Used Onsite (kWh)', },
  { field: 'electricityUseOnsiteGenerated', title: 'Electricity Use – Generated from Onsite Renewable Systems (kWh)', },
  { field: 'electricityUseOnsiteGeneratedExported', title: 'Electricity Use – Generated from Onsite Renewable Systems and Exported (kWh)', },
  { field: 'greenPower', title: 'Green Power - Onsite and Offsite (kWh)', },
  { field: 'totalGHGEmissions', title: 'Total (Location-Based) GHG Emissions (Metric Tons CO2e)', },
  { field: 'directGHGEmissions', title: 'Direct GHG Emissions (Metric Tons CO2e)', },
  { field: 'indirectGHGEmissions', title: 'Indirect (Location-Based) GHG Emissions (Metric Tons CO2e)', },
  { field: 'netEmissions', title: 'Net Emissions (Metric Tons CO2e)', },
  { field: 'avoidedEmissions', title: 'Avoided Emissions - Onsite and Offsite Green Power (Metric Tons CO2e)', },
  { field: 'percentElectricityGeneratedFromRenewableOnsitePower', title: 'Percent of Total Electricity Generated from Onsite Renewable Systems', },
  { field: 'propertyNotes', title: 'Property Notes', },
  { field: 'waterUse', title: 'Water Use (All Water Sources) (kgal)', },
  { field: 'totalActiveEnergyMeters', title: 'Number of Active Energy Meters - Total', },
  { field: 'borough', title: 'Borough', },
  { field: 'latitude', title: 'Latitude', },
  { field: 'longitude', title: 'Longitude', },
  { field: 'councilDistrict', title: 'Council District', },
];

export const data = [
  {
    "propertyId": 6414481,
    "propertyName": "Shore Hill Apartments",
    "bbl": "3-06078-0010",
    "bin": "3322532;3322533;3322534",
    "address": "9000 Shore Road",
    "city": "Brooklyn",
    "zip": 11209,
    "primaryPropertyType": "Multifamily Housing",
    "primaryPropertyTypeArea": 407584,
    "secondaryPropertyType": "Medical Office",
    "secondaryPropertyTypeArea": 6543,
    "yearBuilt": 1977,
    "numberOfBuildings": 2,
    "occupancy": 100,
    "meteredAreasEnergy": "Whole Property",
    "meteredAreasWater": "Whole Property",
    "energyStarScore": 60,
    "oilUseNo1": "Not Available",
    "oilUseNo2": 865398,
    "steamUse": "Not Available",
    "hotWaterUse": "Not Available",
    "chilledWaterUse": "Not Available",
    "naturalGasUse": 29748925.4,
    "electricityUseGridPurchased": 2129699.7,
    "electricityUseGridPurchasedAndOnsiteGenerated": 2173598,
    "electricityUseOnsiteGeneratedUsed": 43898,
    "electricityUseOnsiteGenerated": 43898,
    "electricityUseOnsiteGeneratedExported": 0,
    "greenPower": 43898,
    "totalGHGEmissions": 2258.6,
    "directGHGEmissions": 1644.3,
    "indirectGHGEmissions": 614.3,
    "netEmissions": 2258.6,
    "avoidedEmissions": 19.3,
    "percentElectricityGeneratedFromRenewableOnsitePower": 2.0196,
    "propertyNotes": "totalActiveEnergyMeters is greater than Number of Active Energy Meters - Used to Compute Metrics because owner accounts that represent a subset of aggregated accounts are also tracked in Portfolio Manager. Including these meters in metrics would double count energy use from this site.",
    "waterUse": 22875.4,
    "totalActiveEnergyMeters": 9,
    "borough": "BROOKLYN",
    "latitude": 40.622118,
    "longitude": -74.040172,
    "councilDistrict": 47
  },
  {
    "propertyId": 20067090,
    "propertyNam": "38-01 23rd Avenue",
    "bbl": "4-00805-0001",
    "bin": 4436960,
    "address": "38-01 23rd Avenue",
    "city": "Queens",
    "zip": 11105,
    "primaryPropertyType": "Office",
    "primaryPropertyTypeArea": 41500,
    "secondaryPropertyType": "Not Available",
    "secondaryPropertyTypeArea": "Not Available",
    "yearBuilt": 1912,
    "numberOfBuildings": 1,
    "occupancy": 90,
    "meteredAreasEnergy": "Whole Property",
    "meteredAreasWater": "Not Available",
    "energyStarScore": 71,
    "oilUseNo1": "Not Available",
    "oilUseNo2": 2678566.2,
    "steamUse": "Not Available",
    "hotWaterUse": "Not Available",
    "chilledWaterUse": "Not Available",
    "naturalGasUse": 14800,
    "electricityUseGridPurchased": 267718,
    "electricityUseGridPurchasedAndOnsiteGenerated": 354338,
    "electricityUseOnsiteGeneratedUsed": 86620,
    "electricityUseOnsiteGenerated": 86620,
    "electricityUseOnsiteGeneratedExported": 0,
    "greenPower": 86620,
    "totalGHGEmissions": 276.8,
    "directGHGEmissions": 199.6,
    "indirectGHGEmissions": 77.2,
    "netEmissions": 276.8,
    "avoidedEmissions": 38.2,
    "percentElectricityGeneratedFromRenewableOnsitePower": 24.44559,
    "propertyNotes": "NYC borough, Block and Lot (BBL): 4-00805-0001\nbin: 4436960",
    "waterUse": "Not Available",
    "totalActiveEnergyMeters": 6,
    "borough": "QUEENS",
    "latitude": 40.771527,
    "longitude": -73.908832,
    "councilDistrict": 22
  },
  {
    "propertyId": 1633020,
    "propertyName": "X144 (OECID: 0200188; BBL: 2044930001)",
    "bbl": 2044930001,
    "bin": 2053518,
    "address": "2545 Gunther Avenue",
    "city": "Bronx",
    "zip": 10469,
    "primaryPropertyType": "K-12 School",
    "primaryPropertyTypeArea": 188575,
    "secondaryPropertyType": "Not Available",
    "secondaryPropertyTypeArea": "Not Available",
    "yearBuilt": 1965,
    "numberOfBuildings": 1,
    "occupancy": 100,
    "meteredAreasEnergy": "Whole Property",
    "meteredAreasWater": "Not Available",
    "energyStarScore": 84,
    "oilUseNo1": "Not Available",
    "oilUseNo2": 7529142.2,
    "steamUse": "Not Available",
    "hotWaterUse": "Not Available",
    "chilledWaterUse": "Not Available",
    "naturalGasUse": 236800,
    "electricityUseGridPurchased": 662799.9,
    "electricityUseGridPurchasedAndOnsiteGenerated": 829932.3,
    "electricityUseOnsiteGeneratedUsed": 167132.3,
    "electricityUseOnsiteGenerated": 184566.9,
    "electricityUseOnsiteGeneratedExported": 17434.6,
    "greenPower": 167132.3,
    "totalGHGEmissions": 762.5,
    "directGHGEmissions": 571.3,
    "indirectGHGEmissions": 191.2,
    "netEmissions": 762.5,
    "avoidedEmissions": 73.6,
    "percentElectricityGeneratedFromRenewableOnsitePower": 20.13806,
    "propertyNotes": "Not Available",
    "waterUse": "Not Available",
    "totalActiveEnergyMeters": 4,
    "borough": "BRONX",
    "latitude": 40.863735,
    "longitude": -73.83607,
    "councilDistrict": 13
  },
  {
    "propertyId": 1633102,
    "propertyName": "K152 (OECID: 0300154; BBL: 3075510026)",
    "bbl": 3075510026,
    "bin": 3205780,
    "address": "725 East 23rd Street",
    "city": "Brooklyn",
    "zip": 11210,
    "primaryPropertyType": "K-12 School",
    "primaryPropertyTypeArea": 184800,
    "secondaryPropertyType": "Not Available",
    "secondaryPropertyTypeArea": "Not Available",
    "yearBuilt": 1907,
    "numberOfBuildings": 1,
    "occupancy": 100,
    "meteredAreasEnergy": "Whole Property",
    "meteredAreasWater": "",
    "energyStarScore": 18,
    "oilUseNo1": "Not Available",
    "oilUseNo2": 524400,
    "steamUse": "Not Available",
    "hotWaterUse": "Not Available",
    "chilledWaterUse": "Not Available",
    "naturalGasUse": 13278100.8,
    "electricityUseGridPurchased": 1744799.7,
    "electricityUseGridPurchasedAndOnsiteGenerated": 1837041,
    "electricityUseOnsiteGeneratedUsed": 92241,
    "electricityUseOnsiteGenerated": 92241,
    "electricityUseOnsiteGeneratedExported": 0,
    "greenPower": 92241,
    "totalGHGEmissions": 1247.5,
    "directGHGEmissions": 744.2,
    "indirectGHGEmissions": 503.3,
    "netEmissions": 1247.5,
    "avoidedEmissions": 40.6,
    "percentElectricityGeneratedFromRenewableOnsitePower": 5.021173,
    "propertyNotes": "TCUs K927 removed in 2017",
    "waterUse": 303.1,
    "totalActiveEnergyMeters": 4,
    "borough": "BROOKLYN",
    "latitude": 40.632562,
    "longitude": -73.954724,
    "councilDistrict": 45
  },
  {
    "propertyId": 1633201,
    "propertyName": "Q226 (OECID: 0400249; BBL: 4117140100)",
    "bbl": 4117140100,
    "bin": 4253607,
    "address": "121-10 Rockaway Boulevard",
    "city": "Queens",
    "zip": 11420,
    "primaryPropertyType": "K-12 School",
    "primaryPropertyTypeArea": 250800,
    "secondaryPropertyType": "Not Available",
    "secondaryPropertyTypeArea": "Not Available",
    "yearBuilt": 1973,
    "numberOfBuildings": 1,
    "occupancy": 100,
    "meteredAreasEnergy": "Whole Property",
    "meteredAreasWater": "",
    "energyStarScore": 86,
    "oilUseNo1": "Not Available",
    "oilUseNo2": 800400.2,
    "steamUse": "Not Available",
    "hotWaterUse": "Not Available",
    "chilledWaterUse": "Not Available",
    "naturalGasUse": 8888800.1,
    "electricityUseGridPurchased": 1215679.9,
    "electricityUseGridPurchasedAndOnsiteGenerated": 1350817.1,
    "electricityUseOnsiteGeneratedUsed": 135137.1,
    "electricityUseOnsiteGenerated": 135433.5,
    "electricityUseOnsiteGeneratedExported": 296.4,
    "greenPower": 135137.1,
    "totalGHGEmissions": 882.2,
    "directGHGEmissions": 531.5,
    "indirectGHGEmissions": 350.7,
    "netEmissions": 882.2,
    "avoidedEmissions": 59.5,
    "percentElectricityGeneratedFromRenewableOnsitePower": 10.0041,
    "propertyNotes": "TCUs Q923 removed in 2016",
    "waterUse": 1143,
    "totalActiveEnergyMeters": 4,
    "borough": "QUEENS",
    "latitude": 40.675771,
    "longitude": -73.816938,
    "councilDistrict": 28
  },
  {
    "propertyId": 1633555,
    "propertyName": "K324 (OECID: 0300122; BBL: 3016360001)",
    "bbl": 3016360001,
    "bin": 3044657,
    "address": "800 Gates Avenue",
    "city": "Brooklyn",
    "zip": 11221,
    "primaryPropertyType": "K-12 School",
    "primaryPropertyTypeArea": 205200,
    "secondaryPropertyType": "Not Available",
    "secondaryPropertyTypeArea": "Not Available",
    "yearBuilt": 1974,
    "numberOfBuildings": 1,
    "occupancy": 100,
    "meteredAreasEnergy": "Whole Property",
    "meteredAreasWater": "",
    "energyStarScore": 66,
    "oilUseNo1": "Not Available",
    "oilUseNo2": 5865000.1,
    "steamUse": "Not Available",
    "hotWaterUse": "Not Available",
    "chilledWaterUse": "Not Available",
    "naturalGasUse": 0,
    "electricityUseGridPurchased": 1536799.7,
    "electricityUseGridPurchasedAndOnsiteGenerated": 1672156.1,
    "electricityUseOnsiteGeneratedUsed": 135356.1,
    "electricityUseOnsiteGenerated": 135356.1,
    "electricityUseOnsiteGeneratedExported": 0,
    "greenPower": 135356.1,
    "totalGHGEmissions": 878.5,
    "directGHGEmissions": 435.2,
    "indirectGHGEmissions": 443.3,
    "netEmissions": 878.5,
    "avoidedEmissions": 59.6,
    "percentElectricityGeneratedFromRenewableOnsitePower": 8.094705,
    "propertyNotes": "Not Available",
    "waterUse": 837.9,
    "totalActiveEnergyMeters": 4,
    "borough": "BROOKLYN",
    "latitude": 40.68832,
    "longitude": -73.932275,
    "councilDistrict": 36
  },
  {
    "propertyId": 1633608,
    "propertyName": "K455, K456 (OECID: 0300339; BBL: 3017010001)",
    "bbl": 3017010001,
    "bin": 3047996,
    "address": "1700 Fulton Street",
    "city": "Brooklyn",
    "zip": 11213,
    "primaryPropertyType": "K-12 School",
    "primaryPropertyTypeArea": 460800,
    "secondaryPropertyType": "Not Available",
    "secondaryPropertyTypeArea": "Not Available",
    "yearBuilt": 1974,
    "numberOfBuildings": 1,
    "occupancy": 100,
    "meteredAreasEnergy": "Whole Property",
    "meteredAreasWater": "",
    "energyStarScore": 70,
    "oilUseNo1": "Not Available",
    "oilUseNo2": 0,
    "steamUse": "Not Available",
    "hotWaterUse": "Not Available",
    "chilledWaterUse": "Not Available",
    "naturalGasUse": 21434799.6,
    "electricityUseGridPurchased": 1992799.8,
    "electricityUseGridPurchasedAndOnsiteGenerated": 2486126.4,
    "electricityUseOnsiteGeneratedUsed": 493326.4,
    "electricityUseOnsiteGenerated": 493326.4,
    "electricityUseOnsiteGeneratedExported": 0,
    "greenPower": 493326.4,
    "totalGHGEmissions": 1713.3,
    "directGHGEmissions": 1138.5,
    "indirectGHGEmissions": 574.8,
    "netEmissions": 1713.3,
    "avoidedEmissions": 217.4,
    "percentElectricityGeneratedFromRenewableOnsitePower": 19.84317,
    "propertyNotes": "Not Available",
    "waterUse": 2517.9,
    "totalActiveEnergyMeters": 4,
    "borough": "BROOKLYN",
    "latitude": 40.67944,
    "longitude": -73.932407,
    "councilDistrict": 36
  },
  {
    "propertyId": 1633618,
    "propertyName": "K380 (OECID: 0301169; BBL: 3022360009)",
    "bbl": 3022360009,
    "bin": 3061235,
    "address": "370 Marcy Avenue",
    "city": "Brooklyn",
    "zip": 11206,
    "primaryPropertyType": "K-12 School",
    "primaryPropertyTypeArea": 141600,
    "secondaryPropertyType": "Not Available",
    "secondaryPropertyTypeArea": "Not Available",
    "yearBuilt": 1975,
    "numberOfBuildings": 1,
    "occupancy": 100,
    "meteredAreasEnergy": "Whole Property",
    "meteredAreasWater": "Not Available",
    "energyStarScore": 92,
    "oilUseNo1": "Not Available",
    "oilUseNo2": 4687584.2,
    "steamUse": "Not Available",
    "hotWaterUse": "Not Available",
    "chilledWaterUse": "Not Available",
    "naturalGasUse": 273400,
    "electricityUseGridPurchased": 550399.9,
    "electricityUseGridPurchasedAndOnsiteGenerated": 651639.3,
    "electricityUseOnsiteGeneratedUsed": 101239.3,
    "electricityUseOnsiteGenerated": 105966.5,
    "electricityUseOnsiteGeneratedExported": 4727.2,
    "greenPower": 101239.3,
    "totalGHGEmissions": 521.1,
    "directGHGEmissions": 362.4,
    "indirectGHGEmissions": 158.8,
    "netEmissions": 521.1,
    "avoidedEmissions": 44.6,
    "percentElectricityGeneratedFromRenewableOnsitePower": 15.53609,
    "propertyNotes": "Not Available",
    "waterUse": "Not Available",
    "totalActiveEnergyMeters": 4,
    "borough": "BROOKLYN",
    "latitude": 40.702427,
    "longitude": -73.952985,
    "councilDistrict": 33
  },
  {
    "propertyId": 1633626,
    "propertyName": "Q018 (OECID: 0400019; BBL: 4079550002)",
    "bbl": 4079550002,
    "bin": 4166561,
    "address": "86-35 235th Court",
    "city": "Queens",
    "zip": 11427,
    "primaryPropertyType": "K-12 School",
    "primaryPropertyTypeArea": 68400,
    "secondaryPropertyType": "Not Available",
    "secondaryPropertyTypeArea": "Not Available",
    "yearBuilt": 1960,
    "numberOfBuildings": 1,
    "occupancy": 100,
    "meteredAreasEnergy": "Whole Property",
    "meteredAreasWater": "",
    "energyStarScore": 77,
    "oilUseNo1": "Not Available",
    "oilUseNo2": 2650980.2,
    "steamUse": "Not Available",
    "hotWaterUse": "Not Available",
    "chilledWaterUse": "Not Available",
    "naturalGasUse": 358100,
    "electricityUseGridPurchased": 285840,
    "electricityUseGridPurchasedAndOnsiteGenerated": 407888.1,
    "electricityUseOnsiteGeneratedUsed": 122048.1,
    "electricityUseOnsiteGenerated": 182638,
    "electricityUseOnsiteGeneratedExported": 60589.9,
    "greenPower": 122048.1,
    "totalGHGEmissions": 298.2,
    "directGHGEmissions": 215.7,
    "indirectGHGEmissions": 82.5,
    "netEmissions": 298.2,
    "avoidedEmissions": 53.8,
    "percentElectricityGeneratedFromRenewableOnsitePower": 29.92196,
    "propertyNotes": "Not Available",
    "waterUse": 570,
    "totalActiveEnergyMeters": 4,
    "borough": "QUEENS",
    "latitude": 40.732112,
    "longitude": -73.73246,
    "councilDistrict": 23
  },
  {
    "propertyId": 1633643,
    "propertyName": "Q204 (OECID: 0400202; BBL: 4003430001)",
    "bbl": 4003430001,
    "bin": 4004156,
    "address": "36-41 28th Street",
    "city": "Queens",
    "zip": 11106,
    "primaryPropertyType": "K-12 School",
    "primaryPropertyTypeArea": 183725,
    "secondaryPropertyType": "Not Available",
    "secondaryPropertyTypeArea": "Not Available",
    "yearBuilt": 1957,
    "numberOfBuildings": 1,
    "occupancy": 100,
    "meteredAreasEnergy": "Whole Property",
    "meteredAreasWater": "",
    "energyStarScore": 94,
    "oilUseNo1": "Not Available",
    "oilUseNo2": 1574717.8,
    "steamUse": "Not Available",
    "hotWaterUse": "Not Available",
    "chilledWaterUse": "Not Available",
    "naturalGasUse": 5578100.4,
    "electricityUseGridPurchased": 443599.9,
    "electricityUseGridPurchasedAndOnsiteGenerated": 592890.5,
    "electricityUseOnsiteGeneratedUsed": 149290.5,
    "electricityUseOnsiteGenerated": 175232.6,
    "electricityUseOnsiteGeneratedExported": 25942.1,
    "greenPower": 149290.5,
    "totalGHGEmissions": 541.1,
    "directGHGEmissions": 413.1,
    "indirectGHGEmissions": 128,
    "netEmissions": 541.1,
    "avoidedEmissions": 65.8,
    "percentElectricityGeneratedFromRenewableOnsitePower": 25.18011,
    "propertyNotes": "Not Available",
    "waterUse": 2235.1,
    "totalActiveEnergyMeters": 4,
    "borough": "QUEENS",
    "latitude": 40.757065,
    "longitude": -73.932664,
    "councilDistrict": 26
  },
  {
    "propertyId": 1633748,
    "propertyName": "K032 (OECID: 0300055; BBL: 3004370001)",
    "bbl": 3004370001,
    "bin": "317 Hoyt Street BIN: 3428600 (main bldg); 420 Union Str BIN: 3007326 (Addition)",
    "address": "317 Hoyt Street",
    "city": "Brooklyn",
    "zip": 11231,
    "primaryPropertyType": "K-12 School",
    "primaryPropertyTypeArea": 153579,
    "secondaryPropertyType": "Not Available",
    "secondaryPropertyTypeArea": "Not Available",
    "yearBuilt": 1950,
    "numberOfBuildings": 1,
    "occupancy": 100,
    "meteredAreasEnergy": "Whole Property",
    "meteredAreasWater": "Not Available",
    "energyStarScore": 62,
    "oilUseNo1": "Not Available",
    "oilUseNo2": 4271058.4,
    "steamUse": "Not Available",
    "hotWaterUse": "Not Available",
    "chilledWaterUse": "Not Available",
    "naturalGasUse": 2370300,
    "electricityUseGridPurchased": 1071999.8,
    "electricityUseGridPurchasedAndOnsiteGenerated": 1072000,
    "electricityUseOnsiteGeneratedUsed": 0,
    "electricityUseOnsiteGenerated": 0,
    "electricityUseOnsiteGeneratedExported": 0,
    "greenPower": 0,
    "totalGHGEmissions": 752.1,
    "directGHGEmissions": 442.8,
    "indirectGHGEmissions": 309.2,
    "netEmissions": 752.1,
    "avoidedEmissions": 0,
    "percentElectricityGeneratedFromRenewableOnsitePower": 0,
    "propertyNotes": "1/26/2018 ; TCUs K979 removed in fall 2017\n9/16/2020: new constructed bldg addition (57,579 SF) added in Sept 2020\n4/13/2020: updated SF to include new addition",
    "waterUse": "Not Available",
    "totalActiveEnergyMeters": 5,
    "borough": "BROOKLYN",
    "latitude": 40.680445,
    "longitude": -73.991949,
    "councilDistrict": 39
  },
  {
    "propertyId": 1633867,
    "propertyName": "R455, R456 (OECID: 0500094; BBL: 5066130001)",
    "bbl": 5066130001,
    "bin": 5082634,
    "address": "100 Luten Avenue",
    "city": "Staten Island",
    "zip": 10312,
    "primaryPropertyType": "K-12 School",
    "primaryPropertyTypeArea": 512650,
    "secondaryPropertyType": "Not Available",
    "secondaryPropertyTypeArea": "Not Available",
    "yearBuilt": 1972,
    "numberOfBuildings": 1,
    "occupancy": 100,
    "meteredAreasEnergy": "Whole Property",
    "meteredAreasWater": "",
    "energyStarScore": 88,
    "oilUseNo1": "Not Available",
    "oilUseNo2": 18878399.2,
    "steamUse": "Not Available",
    "hotWaterUse": "Not Available",
    "chilledWaterUse": "Not Available",
    "naturalGasUse": 123100,
    "electricityUseGridPurchased": 2345699.8,
    "electricityUseGridPurchasedAndOnsiteGenerated": 2689310,
    "electricityUseOnsiteGeneratedUsed": 343610,
    "electricityUseOnsiteGenerated": 595458.9,
    "electricityUseOnsiteGeneratedExported": 251848.9,
    "greenPower": 343610,
    "totalGHGEmissions": 2084.1,
    "directGHGEmissions": 1407.5,
    "indirectGHGEmissions": 676.6,
    "netEmissions": 2084.1,
    "avoidedEmissions": 151.4,
    "percentElectricityGeneratedFromRenewableOnsitePower": 12.77688,
    "propertyNotes": "Not Available",
    "waterUse": 2395.2,
    "totalActiveEnergyMeters": 4,
    "borough": "STATEN IS",
    "latitude": 40.528092,
    "longitude": -74.192032,
    "councilDistrict": 51
  },
  {
    "propertyId": 1634229,
    "propertyName": "Q139 (OECID: 0400125; BBL: 4030950050)",
    "bbl": 4030950050,
    "bin": 4072457,
    "address": "93-06 63rd Drive",
    "city": "Queens",
    "zip": 11374,
    "primaryPropertyType": "K-12 School",
    "primaryPropertyTypeArea": 80500,
    "secondaryPropertyType": "Not Available",
    "secondaryPropertyTypeArea": "Not Available",
    "yearBuilt": 1931,
    "numberOfBuildings": 1,
    "occupancy": 100,
    "meteredAreasEnergy": "Whole Property",
    "meteredAreasWater": "",
    "energyStarScore": 97,
    "oilUseNo1": "Not Available",
    "oilUseNo2": 745199.9,
    "steamUse": "Not Available",
    "hotWaterUse": "Not Available",
    "chilledWaterUse": "Not Available",
    "naturalGasUse": 3267600,
    "electricityUseGridPurchased": 16160,
    "electricityUseGridPurchasedAndOnsiteGenerated": 142255,
    "electricityUseOnsiteGeneratedUsed": 126095,
    "electricityUseOnsiteGenerated": 126095,
    "electricityUseOnsiteGeneratedExported": 0,
    "greenPower": 126095,
    "totalGHGEmissions": 233.5,
    "directGHGEmissions": 228.9,
    "indirectGHGEmissions": 4.7,
    "netEmissions": 233.5,
    "avoidedEmissions": 55.6,
    "percentElectricityGeneratedFromRenewableOnsitePower": 88.64012,
    "propertyNotes": "Not Available",
    "waterUse": 3,
    "totalActiveEnergyMeters": 4,
    "borough": "QUEENS",
    "latitude": 40.72814,
    "longitude": -73.863582,
    "councilDistrict": 30
  },
  {
    "propertyId": 1634281,
    "propertyName": "Q025 (OECID: 0400025; BBL: 4052610001)",
    "bbl": 4052610001,
    "bin": 4119139,
    "address": "34-65 192nd Street",
    "city": "Queens",
    "zip": 11358,
    "primaryPropertyType": "K-12 School",
    "primaryPropertyTypeArea": 161175,
    "secondaryPropertyType": "Not Available",
    "secondaryPropertyTypeArea": "Not Available",
    "yearBuilt": 1951,
    "numberOfBuildings": 1,
    "occupancy": 100,
    "meteredAreasEnergy": "Whole Property",
    "meteredAreasWater": "",
    "energyStarScore": 72,
    "oilUseNo1": "Not Available",
    "oilUseNo2": 8992963.4,
    "steamUse": "Not Available",
    "hotWaterUse": "Not Available",
    "chilledWaterUse": "Not Available",
    "naturalGasUse": 202800,
    "electricityUseGridPurchased": 850399.9,
    "electricityUseGridPurchasedAndOnsiteGenerated": 1068343.8,
    "electricityUseOnsiteGeneratedUsed": 217943.8,
    "electricityUseOnsiteGenerated": 243950,
    "electricityUseOnsiteGeneratedExported": 26006.2,
    "greenPower": 217943.8,
    "totalGHGEmissions": 923.4,
    "directGHGEmissions": 678.1,
    "indirectGHGEmissions": 245.3,
    "netEmissions": 923.4,
    "avoidedEmissions": 96,
    "percentElectricityGeneratedFromRenewableOnsitePower": 20.40016,
    "propertyNotes": "Not Available",
    "waterUse": 129.7,
    "totalActiveEnergyMeters": 5,
    "borough": "QUEENS",
    "latitude": 40.765133,
    "longitude": -73.790083,
    "councilDistrict": 19
  },
  {
    "propertyId": 1634444,
    "propertyName": "K058 (OECID: 0300078; BBL: 3004490015)",
    "bbl": 3004490015,
    "bin": 3007547,
    "address": "330 Smith Street",
    "city": "Brooklyn",
    "zip": 11231,
    "primaryPropertyType": "K-12 School",
    "primaryPropertyTypeArea": 133200,
    "secondaryPropertyType": "Not Available",
    "secondaryPropertyTypeArea": "Not Available",
    "yearBuilt": 1957,
    "numberOfBuildings": 1,
    "occupancy": 100,
    "meteredAreasEnergy": "Whole Property",
    "meteredAreasWater": "Not Available",
    "energyStarScore": 99,
    "oilUseNo1": "Not Available",
    "oilUseNo2": 0,
    "steamUse": "Not Available",
    "hotWaterUse": "Not Available",
    "chilledWaterUse": "Not Available",
    "naturalGasUse": 3521499.9,
    "electricityUseGridPurchased": 195360,
    "electricityUseGridPurchasedAndOnsiteGenerated": 342944.2,
    "electricityUseOnsiteGeneratedUsed": 147584.2,
    "electricityUseOnsiteGenerated": 252333,
    "electricityUseOnsiteGeneratedExported": 104748.8,
    "greenPower": 147584.2,
    "totalGHGEmissions": 243.4,
    "directGHGEmissions": 187,
    "indirectGHGEmissions": 56.4,
    "netEmissions": 243.4,
    "avoidedEmissions": 65,
    "percentElectricityGeneratedFromRenewableOnsitePower": 43.03446,
    "propertyNotes": "Not Available",
    "waterUse": "Not Available",
    "totalActiveEnergyMeters": 4,
    "borough": "BROOKLYN",
    "latitude": 40.680415,
    "longitude": -73.994754,
    "councilDistrict": 39
  },
  {
    "propertyId": 1634506,
    "propertyName": "K505 (OECID: 0300354; BBL: 3055060006)",
    "bbl": 3055060006,
    "bin": 3131537,
    "address": "5800 20th Avenue",
    "city": "Brooklyn",
    "zip": 11204,
    "primaryPropertyType": "K-12 School",
    "primaryPropertyTypeArea": 339600,
    "secondaryPropertyType": "Not Available",
    "secondaryPropertyTypeArea": "Not Available",
    "yearBuilt": 1965,
    "numberOfBuildings": 1,
    "occupancy": 100,
    "meteredAreasEnergy": "Whole Property",
    "meteredAreasWater": "",
    "energyStarScore": 85,
    "oilUseNo1": "Not Available",
    "oilUseNo2": 17979054.1,
    "steamUse": "Not Available",
    "hotWaterUse": "Not Available",
    "chilledWaterUse": "Not Available",
    "naturalGasUse": 113400,
    "electricityUseGridPurchased": 974399.9,
    "electricityUseGridPurchasedAndOnsiteGenerated": 1236584.7,
    "electricityUseOnsiteGeneratedUsed": 262184.7,
    "electricityUseOnsiteGenerated": 269785.3,
    "electricityUseOnsiteGeneratedExported": 7600.6,
    "greenPower": 262184.7,
    "totalGHGEmissions": 1621.3,
    "directGHGEmissions": 1340.2,
    "indirectGHGEmissions": 281.1,
    "netEmissions": 1621.3,
    "avoidedEmissions": 115.5,
    "percentElectricityGeneratedFromRenewableOnsitePower": 21.20232,
    "propertyNotes": "Not Available",
    "waterUse": 83.4,
    "totalActiveEnergyMeters": 4,
    "borough": "BROOKLYN",
    "latitude": 40.620446,
    "longitude": -73.981795,
    "councilDistrict": 44
  },
  {
    "propertyId": 1634519,
    "propertyName": "Q021 (OECID: 0400022; BBL: 4048030001)",
    "bbl": 4048030001,
    "bin": 4108665,
    "address": "147-26 26th Avenue",
    "city": "Queens",
    "zip": 11354,
    "primaryPropertyType": "K-12 School",
    "primaryPropertyTypeArea": 125260,
    "secondaryPropertyType": "Not Available",
    "secondaryPropertyTypeArea": "Not Available",
    "yearBuilt": 1962,
    "numberOfBuildings": 1,
    "occupancy": 100,
    "meteredAreasEnergy": "Whole Property",
    "meteredAreasWater": "Not Available",
    "energyStarScore": 70,
    "oilUseNo1": "Not Available",
    "oilUseNo2": 1504200,
    "steamUse": "Not Available",
    "hotWaterUse": "Not Available",
    "chilledWaterUse": "Not Available",
    "naturalGasUse": 287700,
    "electricityUseGridPurchased": 712799.9,
    "electricityUseGridPurchasedAndOnsiteGenerated": 852452.2,
    "electricityUseOnsiteGeneratedUsed": 139652.2,
    "electricityUseOnsiteGenerated": 142244,
    "electricityUseOnsiteGeneratedExported": 2591.8,
    "greenPower": 139652.2,
    "totalGHGEmissions": 579.9,
    "directGHGEmissions": 374.3,
    "indirectGHGEmissions": 205.6,
    "netEmissions": 579.9,
    "avoidedEmissions": 61.5,
    "percentElectricityGeneratedFromRenewableOnsitePower": 16.38241,
    "propertyNotes": "Not Available",
    "waterUse": "Not Available",
    "totalActiveEnergyMeters": 5,
    "borough": "QUEENS",
    "latitude": 40.774512,
    "longitude": -73.819295,
    "councilDistrict": 19
  },
  {
    "propertyId": 1634550,
    "propertyName": "Q490, Q491 (OECID: 0400216; BBL: 4110490001)",
    "bbl": 4110490001,
    "bin": 4238003,
    "address": "207-01 116th Avenue",
    "city": "Queens",
    "zip": 11411,
    "primaryPropertyType": "K-12 School",
    "primaryPropertyTypeArea": 312200,
    "secondaryPropertyType": "Heated Swimming Pool",
    "secondaryPropertyTypeArea": 0,
    "yearBuilt": 1939,
    "numberOfBuildings": 1,
    "occupancy": 100,
    "meteredAreasEnergy": "Whole Property",
    "meteredAreasWater": "",
    "energyStarScore": 60,
    "oilUseNo1": "Not Available",
    "oilUseNo2": 1438787.8,
    "steamUse": "Not Available",
    "hotWaterUse": "Not Available",
    "chilledWaterUse": "Not Available",
    "naturalGasUse": 20163697.8,
    "electricityUseGridPurchased": 1313599.9,
    "electricityUseGridPurchasedAndOnsiteGenerated": 1699507.9,
    "electricityUseOnsiteGeneratedUsed": 385907.9,
    "electricityUseOnsiteGenerated": 408142,
    "electricityUseOnsiteGeneratedExported": 22234.1,
    "greenPower": 385907.9,
    "totalGHGEmissions": 1556.7,
    "directGHGEmissions": 1177.8,
    "indirectGHGEmissions": 378.9,
    "netEmissions": 1556.7,
    "avoidedEmissions": 170,
    "percentElectricityGeneratedFromRenewableOnsitePower": 22.70704,
    "propertyNotes": "Not Available",
    "waterUse": 1193.1,
    "totalActiveEnergyMeters": 4,
    "borough": "QUEENS",
    "latitude": 40.697819,
    "longitude": -73.745728,
    "councilDistrict": 27
  },
  {
    "propertyId": 1634606,
    "propertyName": "M070 (OECID: 0100079; BBL: 1007410010)",
    "bbl": 1007410010,
    "bin": 1079152,
    "address": "333 West 17th Street",
    "city": "New York",
    "zip": 10011,
    "primaryPropertyType": "K-12 School",
    "primaryPropertyTypeArea": 180175,
    "secondaryPropertyType": "Not Available",
    "secondaryPropertyTypeArea": "Not Available",
    "yearBuilt": 1966,
    "numberOfBuildings": 1,
    "occupancy": 100,
    "meteredAreasEnergy": "Whole Property",
    "meteredAreasWater": "Not Available",
    "energyStarScore": 78,
    "oilUseNo1": "Not Available",
    "oilUseNo2": 2104085.9,
    "steamUse": "Not Available",
    "hotWaterUse": "Not Available",
    "chilledWaterUse": "Not Available",
    "naturalGasUse": 284900,
    "electricityUseGridPurchased": 657359.9,
    "electricityUseGridPurchasedAndOnsiteGenerated": 788998.8,
    "electricityUseOnsiteGeneratedUsed": 131638.8,
    "electricityUseOnsiteGenerated": 137155.3,
    "electricityUseOnsiteGeneratedExported": 5516.5,
    "greenPower": 131638.8,
    "totalGHGEmissions": 1031.6,
    "directGHGEmissions": 842,
    "indirectGHGEmissions": 189.6,
    "netEmissions": 1031.6,
    "avoidedEmissions": 58,
    "percentElectricityGeneratedFromRenewableOnsitePower": 16.68428,
    "propertyNotes": "Not Available",
    "waterUse": "Not Available",
    "totalActiveEnergyMeters": 5,
    "borough": "MANHATTAN",
    "latitude": 40.742129,
    "longitude": -74.002198,
    "councilDistrict": 3
  },
  {
    "propertyId": 1634645,
    "propertyName": "X184 (OECID: 0200203; BBL: 2026550030)",
    "bbl": 2026550030,
    "bin": 2004690,
    "address": "778 Forest Avenue",
    "city": "Bronx",
    "zip": 10456,
    "primaryPropertyType": "K-12 School",
    "primaryPropertyTypeArea": 210000,
    "secondaryPropertyType": "Not Available",
    "secondaryPropertyTypeArea": "Not Available",
    "yearBuilt": 1974,
    "numberOfBuildings": 1,
    "occupancy": 100,
    "meteredAreasEnergy": "Whole Property",
    "meteredAreasWater": "Not Available",
    "energyStarScore": 89,
    "oilUseNo1": "Not Available",
    "oilUseNo2": 7876901.7,
    "steamUse": "Not Available",
    "hotWaterUse": "Not Available",
    "chilledWaterUse": "Not Available",
    "naturalGasUse": 39600,
    "electricityUseGridPurchased": 707999.9,
    "electricityUseGridPurchasedAndOnsiteGenerated": 929592,
    "electricityUseOnsiteGeneratedUsed": 221592,
    "electricityUseOnsiteGenerated": 261225.4,
    "electricityUseOnsiteGeneratedExported": 39633.4,
    "greenPower": 221592,
    "totalGHGEmissions": 790.9,
    "directGHGEmissions": 586.6,
    "indirectGHGEmissions": 204.2,
    "netEmissions": 790.9,
    "avoidedEmissions": 97.6,
    "percentElectricityGeneratedFromRenewableOnsitePower": 23.83755,
    "propertyNotes": "Not Available",
    "waterUse": "Not Available",
    "totalActiveEnergyMeters": 4,
    "borough": "BRONX",
    "latitude": 40.819006,
    "longitude": -73.905869,
    "councilDistrict": 17
  },
  {
    "propertyId": 1836438,
    "propertyName": "Q074 (OECID: 0400065; BBL: 4077230001)",
    "bbl": 4077230001,
    "bin": 4163953,
    "address": "61-15 Oceania Street",
    "city": "Queens",
    "zip": 11362,
    "primaryPropertyType": "K-12 School",
    "primaryPropertyTypeArea": 145325,
    "secondaryPropertyType": "Not Available",
    "secondaryPropertyTypeArea": "Not Available",
    "yearBuilt": 1953,
    "numberOfBuildings": 1,
    "occupancy": 100,
    "meteredAreasEnergy": "Whole Property",
    "meteredAreasWater": "",
    "energyStarScore": 70,
    "oilUseNo1": "Not Available",
    "oilUseNo2": 7503750.2,
    "steamUse": "Not Available",
    "hotWaterUse": "Not Available",
    "chilledWaterUse": "Not Available",
    "naturalGasUse": 47000,
    "electricityUseGridPurchased": 575639.9,
    "electricityUseGridPurchasedAndOnsiteGenerated": 674424.5,
    "electricityUseOnsiteGeneratedUsed": 98784.5,
    "electricityUseOnsiteGenerated": 152578,
    "electricityUseOnsiteGeneratedExported": 53793.5,
    "greenPower": 98784.5,
    "totalGHGEmissions": 725.4,
    "directGHGEmissions": 559.3,
    "indirectGHGEmissions": 166,
    "netEmissions": 725.4,
    "avoidedEmissions": 43.5,
    "percentElectricityGeneratedFromRenewableOnsitePower": 14.64723,
    "propertyNotes": "Not Available",
    "waterUse": 1213.7,
    "totalActiveEnergyMeters": 4,
    "borough": "QUEENS",
    "latitude": 40.745201,
    "longitude": -73.767446,
    "councilDistrict": 23
  },
  {
    "propertyId": 1836589,
    "propertyName": "K224 (OECID: 0300229; BBL: 3045300001)",
    "bbl": 3045300001,
    "bin": 3098980,
    "address": "757 Wortman Avenue",
    "city": "Brooklyn",
    "zip": 11208,
    "primaryPropertyType": "K-12 School",
    "primaryPropertyTypeArea": 121200,
    "secondaryPropertyType": "Not Available",
    "secondaryPropertyTypeArea": "Not Available",
    "yearBuilt": 1930,
    "numberOfBuildings": 1,
    "occupancy": 100,
    "meteredAreasEnergy": "Whole Property",
    "meteredAreasWater": "Not Available",
    "energyStarScore": 77,
    "oilUseNo1": "Not Available",
    "oilUseNo2": 0,
    "steamUse": "Not Available",
    "hotWaterUse": "Not Available",
    "chilledWaterUse": "Not Available",
    "naturalGasUse": 5238499.8,
    "electricityUseGridPurchased": 595999.9,
    "electricityUseGridPurchasedAndOnsiteGenerated": 694757.8,
    "electricityUseOnsiteGeneratedUsed": 98757.8,
    "electricityUseOnsiteGenerated": 103133.4,
    "electricityUseOnsiteGeneratedExported": 4375.7,
    "greenPower": 98757.8,
    "totalGHGEmissions": 450.2,
    "directGHGEmissions": 278.2,
    "indirectGHGEmissions": 171.9,
    "netEmissions": 450.2,
    "avoidedEmissions": 43.5,
    "percentElectricityGeneratedFromRenewableOnsitePower": 14.2147,
    "propertyNotes": "10/2/20: corrected address & BIN",
    "waterUse": "Not Available",
    "totalActiveEnergyMeters": 4,
    "borough": "BROOKLYN",
    "latitude": 40.664075,
    "longitude": -73.866092,
    "councilDistrict": 42
  },
  {
    "propertyId": 1836826,
    "propertyName": "Q405 (OECID: 0400211; BBL: 4060440001)",
    "bbl": 4060440001,
    "bin": 4134578,
    "address": "32-24 Corp Kennedy Street",
    "city": "Queens",
    "zip": 11361,
    "primaryPropertyType": "K-12 School",
    "primaryPropertyTypeArea": 296400,
    "secondaryPropertyType": "Heated Swimming Pool",
    "secondaryPropertyTypeArea": 0,
    "yearBuilt": 1935,
    "numberOfBuildings": 1,
    "occupancy": 100,
    "meteredAreasEnergy": "Whole Property",
    "meteredAreasWater": "",
    "energyStarScore": 97,
    "oilUseNo1": "Not Available",
    "oilUseNo2": 10184123.8,
    "steamUse": "Not Available",
    "hotWaterUse": "Not Available",
    "chilledWaterUse": "Not Available",
    "naturalGasUse": 3766900.3,
    "electricityUseGridPurchased": 809599.9,
    "electricityUseGridPurchasedAndOnsiteGenerated": 1222350.5,
    "electricityUseOnsiteGeneratedUsed": 412750.5,
    "electricityUseOnsiteGenerated": 518132,
    "electricityUseOnsiteGeneratedExported": 105381.5,
    "greenPower": 412750.5,
    "totalGHGEmissions": 1189.4,
    "directGHGEmissions": 955.8,
    "indirectGHGEmissions": 233.5,
    "netEmissions": 1189.4,
    "avoidedEmissions": 181.9,
    "percentElectricityGeneratedFromRenewableOnsitePower": 33.76695,
    "propertyNotes": "TCUs Q761 removed in 2017",
    "waterUse": 559.8,
    "totalActiveEnergyMeters": 4,
    "borough": "QUEENS",
    "latitude": 40.771755,
    "longitude": -73.780296,
    "councilDistrict": 19
  },
  {
    "propertyId": 1836836,
    "propertyName": "R445 (OECID: 0500079; BBL: 5011210001)",
    "bbl": 5011210001,
    "bin": 5026076,
    "address": "85 St Joseph's Avenue",
    "city": "Staten Island",
    "zip": 10302,
    "primaryPropertyType": "K-12 School",
    "primaryPropertyTypeArea": 294685,
    "secondaryPropertyType": "Not Available",
    "secondaryPropertyTypeArea": "Not Available",
    "yearBuilt": 1927,
    "numberOfBuildings": 1,
    "occupancy": 100,
    "meteredAreasEnergy": "Whole Property",
    "meteredAreasWater": "",
    "energyStarScore": 51,
    "oilUseNo1": "Not Available",
    "oilUseNo2": 3221333.9,
    "steamUse": "Not Available",
    "hotWaterUse": "Not Available",
    "chilledWaterUse": "Not Available",
    "naturalGasUse": 19085600.3,
    "electricityUseGridPurchased": 1964799.9,
    "electricityUseGridPurchasedAndOnsiteGenerated": 2067549.9,
    "electricityUseOnsiteGeneratedUsed": 102749.9,
    "electricityUseOnsiteGenerated": 103633.3,
    "electricityUseOnsiteGeneratedExported": 883.4,
    "greenPower": 102749.9,
    "totalGHGEmissions": 1819.5,
    "directGHGEmissions": 1252.8,
    "indirectGHGEmissions": 566.8,
    "netEmissions": 1819.5,
    "avoidedEmissions": 45.3,
    "percentElectricityGeneratedFromRenewableOnsitePower": 4.969645,
    "propertyNotes": "Not Available",
    "waterUse": 1777.6,
    "totalActiveEnergyMeters": 4,
    "borough": "STATEN IS",
    "latitude": 40.634573,
    "longitude": -74.141818,
    "councilDistrict": 49
  },
  {
    "propertyId": 21353730,
    "propertyName": "Benchmarking Group - 112",
    "bbl": 3016160001,
    "bin": "3399443; 3393805; 3043822",
    "address": "125 Stuyvesant Ave",
    "city": "Brooklyn",
    "zip": 11221,
    "primaryPropertyType": "K-12 School",
    "primaryPropertyTypeArea": 308400,
    "secondaryPropertyType": "Other - Recreation",
    "secondaryPropertyTypeArea": 404,
    "yearBuilt": 1954,
    "numberOfBuildings": 3,
    "occupancy": 100,
    "meteredAreasEnergy": "Whole Property",
    "meteredAreasWater": "",
    "energyStarScore": 79,
    "oilUseNo1": "Not Available",
    "oilUseNo2": 1653654,
    "steamUse": "Not Available",
    "hotWaterUse": "Not Available",
    "chilledWaterUse": "Not Available",
    "naturalGasUse": 13549585.9,
    "electricityUseGridPurchased": 985007.2,
    "electricityUseGridPurchasedAndOnsiteGenerated": 1318939.6,
    "electricityUseOnsiteGeneratedUsed": 333932.2,
    "electricityUseOnsiteGenerated": 333932.2,
    "electricityUseOnsiteGeneratedExported": 0,
    "greenPower": 0,
    "totalGHGEmissions": 1222.9,
    "directGHGEmissions": 842.4,
    "indirectGHGEmissions": 380.5,
    "netEmissions": 1222.9,
    "avoidedEmissions": 0,
    "percentElectricityGeneratedFromRenewableOnsitePower": 25.31823,
    "propertyNotes": "Not Available",
    "waterUse": 1415.1,
    "totalActiveEnergyMeters": 10,
    "borough": "BROOKLYN",
    "latitude": 40.691274,
    "longitude": -73.933697,
    "councilDistrict": 36
  },
  {
    "propertyId": 21353849,
    "propertyName": "Benchmarking Group - 145",
    "bbl": 3077580001,
    "bin": "3386437; 3214729",
    "address": "1037 East 54th St",
    "city": "Brooklyn",
    "zip": 11234,
    "primaryPropertyType": "K-12 School",
    "primaryPropertyTypeArea": 91607,
    "secondaryPropertyType": "Other - Recreation",
    "secondaryPropertyTypeArea": 407,
    "yearBuilt": 1940,
    "numberOfBuildings": 2,
    "occupancy": 100,
    "meteredAreasEnergy": "Whole Property",
    "meteredAreasWater": "",
    "energyStarScore": 40,
    "oilUseNo1": "Not Available",
    "oilUseNo2": 4245625.2,
    "steamUse": "Not Available",
    "hotWaterUse": "Not Available",
    "chilledWaterUse": "Not Available",
    "naturalGasUse": 1690917.9,
    "electricityUseGridPurchased": 341590.1,
    "electricityUseGridPurchasedAndOnsiteGenerated": 560564.4,
    "electricityUseOnsiteGeneratedUsed": 218974.2,
    "electricityUseOnsiteGenerated": 218974.2,
    "electricityUseOnsiteGeneratedExported": 0,
    "greenPower": 0,
    "totalGHGEmissions": 566.6,
    "directGHGEmissions": 404.9,
    "indirectGHGEmissions": 161.7,
    "netEmissions": 566.6,
    "avoidedEmissions": 0,
    "percentElectricityGeneratedFromRenewableOnsitePower": 39.06317,
    "propertyNotes": "Not Available",
    "waterUse": 1956.2,
    "totalActiveEnergyMeters": 7,
    "borough": "BROOKLYN",
    "latitude": 40.632524,
    "longitude": -73.924417,
    "councilDistrict": 45
  },
  {
    "propertyId": 21353850,
    "propertyName": "DOE_6687_K251",
    "bbl": 3077580001,
    "bin": 3214729,
    "address": "1037 East 54th St",
    "city": "Brooklyn",
    "zip": 11234,
    "primaryPropertyType": "K-12 School",
    "primaryPropertyTypeArea": 91200,
    "secondaryPropertyType": "Not Available",
    "secondaryPropertyTypeArea": "Not Available",
    "yearBuilt": 1952,
    "numberOfBuildings": 1,
    "occupancy": 100,
    "meteredAreasEnergy": "Whole Property",
    "meteredAreasWater": "Not Available",
    "energyStarScore": 41,
    "oilUseNo1": "Not Available",
    "oilUseNo2": 4245625.2,
    "steamUse": "Not Available",
    "hotWaterUse": "Not Available",
    "chilledWaterUse": "Not Available",
    "naturalGasUse": "Not Available",
    "electricityUseGridPurchased": 338096,
    "electricityUseGridPurchasedAndOnsiteGenerated": 557070.2,
    "electricityUseOnsiteGeneratedUsed": 218974.2,
    "electricityUseOnsiteGenerated": 218974.2,
    "electricityUseOnsiteGeneratedExported": 0,
    "greenPower": 0,
    "totalGHGEmissions": 561,
    "directGHGEmissions": 400.3,
    "indirectGHGEmissions": 160.7,
    "netEmissions": 561,
    "avoidedEmissions": 0,
    "percentElectricityGeneratedFromRenewableOnsitePower": 39.30819,
    "propertyNotes": "Not Available",
    "waterUse": "Not Available",
    "totalActiveEnergyMeters": 5,
    "borough": "BROOKLYN",
    "latitude": 40.632524,
    "longitude": -73.924417,
    "councilDistrict": 45
  },
  {
    "propertyId": 21353852,
    "propertyName": "Benchmarking Group - 146",
    "bbl": 3079980005,
    "bin": 3224139,
    "address": "6565 Flatlands Ave",
    "city": "Brooklyn",
    "zip": 11236,
    "primaryPropertyType": "K-12 School",
    "primaryPropertyTypeArea": 489600,
    "secondaryPropertyType": "Other - Education",
    "secondaryPropertyTypeArea": 4800,
    "yearBuilt": 1970,
    "numberOfBuildings": 2,
    "occupancy": 100,
    "meteredAreasEnergy": "Whole Property",
    "meteredAreasWater": "",
    "energyStarScore": 78,
    "oilUseNo1": "Not Available",
    "oilUseNo2": 24030076.4,
    "steamUse": "Not Available",
    "hotWaterUse": "Not Available",
    "chilledWaterUse": "Not Available",
    "naturalGasUse": 408295,
    "electricityUseGridPurchased": 2321435.4,
    "electricityUseGridPurchasedAndOnsiteGenerated": 2745182.1,
    "electricityUseOnsiteGeneratedUsed": 423746.1,
    "electricityUseOnsiteGenerated": 423746.1,
    "electricityUseOnsiteGeneratedExported": 0,
    "greenPower": 0,
    "totalGHGEmissions": 2596.8,
    "directGHGEmissions": 1804.9,
    "indirectGHGEmissions": 791.9,
    "netEmissions": 2596.8,
    "avoidedEmissions": 0,
    "percentElectricityGeneratedFromRenewableOnsitePower": 15.43599,
    "propertyNotes": "Not Available",
    "waterUse": 1659.2,
    "totalActiveEnergyMeters": 11,
    "borough": "BROOKLYN",
    "latitude": 40.633285,
    "longitude": -73.916735,
    "councilDistrict": 46
  },
  {
    "propertyId": 21353854,
    "propertyName": "DOE_6802_K515",
    "bbl": 3079980005,
    "bin": 3224139,
    "address": "6565 Flatlands Ave",
    "city": "Brooklyn",
    "zip": 11236,
    "primaryPropertyType": "K-12 School",
    "primaryPropertyTypeArea": 488400,
    "secondaryPropertyType": "Not Available",
    "secondaryPropertyTypeArea": "Not Available",
    "yearBuilt": 1970,
    "numberOfBuildings": 1,
    "occupancy": 100,
    "meteredAreasEnergy": "Whole Property",
    "meteredAreasWater": "Not Available",
    "energyStarScore": 77,
    "oilUseNo1": "Not Available",
    "oilUseNo2": 24030076.4,
    "steamUse": "Not Available",
    "hotWaterUse": "Not Available",
    "chilledWaterUse": "Not Available",
    "naturalGasUse": 408295,
    "electricityUseGridPurchased": 2287159.9,
    "electricityUseGridPurchasedAndOnsiteGenerated": 2710906.1,
    "electricityUseOnsiteGeneratedUsed": 423746.1,
    "electricityUseOnsiteGenerated": 423746.1,
    "electricityUseOnsiteGeneratedExported": 0,
    "greenPower": 0,
    "totalGHGEmissions": 2586.9,
    "directGHGEmissions": 1804.9,
    "indirectGHGEmissions": 782,
    "netEmissions": 2586.9,
    "avoidedEmissions": 0,
    "percentElectricityGeneratedFromRenewableOnsitePower": 15.63116,
    "propertyNotes": "Not Available",
    "waterUse": "Not Available",
    "totalActiveEnergyMeters": 10,
    "borough": "BROOKLYN",
    "latitude": 40.633285,
    "longitude": -73.916735,
    "councilDistrict": 46
  },
  {
    "propertyId": 21354177,
    "propertyName": "Benchmarking Group - 185",
    "bbl": 4109440301,
    "bin": "4526677; 4234318",
    "address": "109-89 204th St",
    "city": "St. Albans",
    "zip": 11412,
    "primaryPropertyType": "K-12 School",
    "primaryPropertyTypeArea": 180427,
    "secondaryPropertyType": "Not Available",
    "secondaryPropertyTypeArea": "Not Available",
    "yearBuilt": 1960,
    "numberOfBuildings": 2,
    "occupancy": 100,
    "meteredAreasEnergy": "Whole Property",
    "meteredAreasWater": "Not Available",
    "energyStarScore": 77,
    "oilUseNo1": "Not Available",
    "oilUseNo2": 6152592.3,
    "steamUse": "Not Available",
    "hotWaterUse": "Not Available",
    "chilledWaterUse": "Not Available",
    "naturalGasUse": 305712,
    "electricityUseGridPurchased": 673922.7,
    "electricityUseGridPurchasedAndOnsiteGenerated": 1042151.5,
    "electricityUseOnsiteGeneratedUsed": 368228.7,
    "electricityUseOnsiteGenerated": 368228.7,
    "electricityUseOnsiteGeneratedExported": 0,
    "greenPower": 0,
    "totalGHGEmissions": 773.4,
    "directGHGEmissions": 472.8,
    "indirectGHGEmissions": 300.6,
    "netEmissions": 773.4,
    "avoidedEmissions": 0,
    "percentElectricityGeneratedFromRenewableOnsitePower": 35.33351,
    "propertyNotes": "Not Available",
    "waterUse": "Not Available",
    "totalActiveEnergyMeters": 6,
    "borough": "QUEENS",
    "latitude": 40.70646,
    "longitude": -73.753579,
    "councilDistrict": 27
  },
  {
    "propertyId": 21354178,
    "propertyName": "DOE_7289_Q192",
    "bbl": 4109440301,
    "bin": 4234318,
    "address": "109-89 204th St",
    "city": "St. Albans",
    "zip": 11412,
    "primaryPropertyType": "K-12 School",
    "primaryPropertyTypeArea": 180125,
    "secondaryPropertyType": "Not Available",
    "secondaryPropertyTypeArea": "Not Available",
    "yearBuilt": 1963,
    "numberOfBuildings": 1,
    "occupancy": 100,
    "meteredAreasEnergy": "Whole Property",
    "meteredAreasWater": "Not Available",
    "energyStarScore": 84,
    "oilUseNo1": "Not Available",
    "oilUseNo2": 6152592.3,
    "steamUse": "Not Available",
    "hotWaterUse": "Not Available",
    "chilledWaterUse": "Not Available",
    "naturalGasUse": 305712,
    "electricityUseGridPurchased": 672291.9,
    "electricityUseGridPurchasedAndOnsiteGenerated": 1040520.7,
    "electricityUseOnsiteGeneratedUsed": 368228.7,
    "electricityUseOnsiteGenerated": 368228.7,
    "electricityUseOnsiteGeneratedExported": 0,
    "greenPower": 0,
    "totalGHGEmissions": 773,
    "directGHGEmissions": 472.8,
    "indirectGHGEmissions": 300.1,
    "netEmissions": 773,
    "avoidedEmissions": 0,
    "percentElectricityGeneratedFromRenewableOnsitePower": 35.38889,
    "propertyNotes": "Not Available",
    "waterUse": "Not Available",
    "totalActiveEnergyMeters": 5,
    "borough": "QUEENS",
    "latitude": 40.70646,
    "longitude": -73.753579,
    "councilDistrict": 27
  },
  {
    "propertyId": 21355266,
    "propertyName": "DOT_3520_Ferry Maintenance Shop",
    "bbl": 5000010068,
    "bin": 5131766,
    "address": "5 Bay St",
    "city": "Staten Island",
    "zip": 10301,
    "primaryPropertyType": "Repair Services (Vehicle, Shoe, Locksmith, etc.)",
    "primaryPropertyTypeArea": 51000,
    "secondaryPropertyType": "Not Available",
    "secondaryPropertyTypeArea": "Not Available",
    "yearBuilt": 1901,
    "numberOfBuildings": 1,
    "occupancy": 100,
    "meteredAreasEnergy": "Whole Property",
    "meteredAreasWater": "Not Available",
    "energyStarScore": "Not Available",
    "oilUseNo1": "Not Available",
    "oilUseNo2": 759000,
    "steamUse": "Not Available",
    "hotWaterUse": "Not Available",
    "chilledWaterUse": "Not Available",
    "naturalGasUse": 1773032,
    "electricityUseGridPurchased": 2007806.9,
    "electricityUseGridPurchasedAndOnsiteGenerated": 2306241.6,
    "electricityUseOnsiteGeneratedUsed": 298434.6,
    "electricityUseOnsiteGenerated": 298434.6,
    "electricityUseOnsiteGeneratedExported": 0,
    "greenPower": 0,
    "totalGHGEmissions": 815.7,
    "directGHGEmissions": 150.5,
    "indirectGHGEmissions": 665.2,
    "netEmissions": 815.7,
    "avoidedEmissions": 0,
    "percentElectricityGeneratedFromRenewableOnsitePower": 12.9403,
    "propertyNotes": "Not Available",
    "waterUse": "Not Available",
    "totalActiveEnergyMeters": 6,
    "borough": "STATEN IS",
    "latitude": 40.641476,
    "longitude": -74.073997,
    "councilDistrict": 49
  },
  {
    "propertyId": 21355288,
    "propertyName": "DPR_3739_Red Hook Recreation Center",
    "bbl": 3005820001,
    "bin": 3008670,
    "address": "155 Bay St",
    "city": "Brooklyn",
    "zip": 11231,
    "primaryPropertyType": "Fitness Center/Health Club/Gym",
    "primaryPropertyTypeArea": 27069,
    "secondaryPropertyType": "Not Available",
    "secondaryPropertyTypeArea": "Not Available",
    "yearBuilt": 1920,
    "numberOfBuildings": 1,
    "occupancy": 100,
    "meteredAreasEnergy": "Whole Property",
    "meteredAreasWater": "",
    "energyStarScore": "Not Available",
    "oilUseNo1": "Not Available",
    "oilUseNo2": 2467826.3,
    "steamUse": "Not Available",
    "hotWaterUse": "Not Available",
    "chilledWaterUse": "Not Available",
    "naturalGasUse": 1525696.8,
    "electricityUseGridPurchased": 336711.9,
    "electricityUseGridPurchasedAndOnsiteGenerated": 337629.2,
    "electricityUseOnsiteGeneratedUsed": 917.2,
    "electricityUseOnsiteGenerated": 917.2,
    "electricityUseOnsiteGeneratedExported": 0,
    "greenPower": 0,
    "totalGHGEmissions": 361.6,
    "directGHGEmissions": 264.2,
    "indirectGHGEmissions": 97.4,
    "netEmissions": 361.6,
    "avoidedEmissions": 0,
    "percentElectricityGeneratedFromRenewableOnsitePower": 0.2716531,
    "propertyNotes": "Not Available",
    "waterUse": 12.6,
    "totalActiveEnergyMeters": 5,
    "borough": "BROOKLYN",
    "latitude": 40.671937,
    "longitude": -74.003515,
    "councilDistrict": 38
  },
  {
    "propertyId": 21355916,
    "propertyName": "DEP > BWT_9614_Port Richmond WPCP Campus",
    "bbl": 5001850400,
    "bin": 0,
    "address": "1801 Richmond Ter",
    "city": "Staten Island",
    "zip": 10310,
    "primaryPropertyType": "Wastewater Treatment Plant",
    "primaryPropertyTypeArea": 358539,
    "secondaryPropertyType": "Not Available",
    "secondaryPropertyTypeArea": "Not Available",
    "yearBuilt": 1953,
    "numberOfBuildings": 6,
    "occupancy": 100,
    "meteredAreasEnergy": "",
    "meteredAreasWater": "",
    "energyStarScore": 61,
    "oilUseNo1": "Not Available",
    "oilUseNo2": 285660,
    "steamUse": "Not Available",
    "hotWaterUse": "Not Available",
    "chilledWaterUse": "Not Available",
    "naturalGasUse": 39223244.7,
    "electricityUseGridPurchased": 21107853.1,
    "electricityUseGridPurchasedAndOnsiteGenerated": 22659960,
    "electricityUseOnsiteGeneratedUsed": 1552100,
    "electricityUseOnsiteGenerated": 1552100,
    "electricityUseOnsiteGeneratedExported": 0,
    "greenPower": 0,
    "totalGHGEmissions": 8640.9,
    "directGHGEmissions": 2104.5,
    "indirectGHGEmissions": 6536.3,
    "netEmissions": 8640.9,
    "avoidedEmissions": 0,
    "percentElectricityGeneratedFromRenewableOnsitePower": 6.849527,
    "propertyNotes": "Not Available",
    "waterUse": 152411.1,
    "totalActiveEnergyMeters": 6,
    "borough": "STATEN IS",
    "latitude": 40.637232,
    "longitude": -74.125556,
    "councilDistrict": 49
  }
];
